enable_audio_bell no
font_size 15
cursor_shape block
cursor_blink_interval 0
shell_integration disabled
cursor_trail 5

# Gruvbox Dark Hard (inlined so we don't need include)
background #1d2021
foreground #fbf1c7
cursor #fbf1c7
selection_foreground #504945
selection_background #3c3836
active_tab_foreground #b8bb26
active_tab_background #665c54
inactive_tab_background #3c3836

color0  #242424
color1  #fb4934
color2  #b8bb26
color3  #fabd2f
color4  #7daea3
color5  #e089a1
color6  #8ec07c
color7  #665c54
color8  #504945
color9  #fb4934
color10 #b8bb26
color11 #fabd2f
color12 #7daea3
color13 #e089a1
color14 #8ec07c
color15 #665c54

confirm_os_window_close 0

font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
