[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines=80 }
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }
size = 18
glyph_offset = { x = 0, y = 0 }

[colors]
indexed_colors = [ { index = 16, color = "#F8BD96"}, { index = 17, color = "#F5E0DC"}]
draw_bold_text_with_bright_colors = true
cursor = { text = "0x1E1D2F" ,cursor = "0xF5E0DC" }

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[cursor]
blink_interval = 500
unfocused_hollow = false

[terminal]
shell = { program = "/usr/bin/zsh" }

[mouse]
hide_when_typing = true
bindings = [ { mouse = "Middle", action = "PasteSelection"} ]
