[font]
size = 25

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Normal"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
